SELECT
        T1.PRODUCT_CODE AS PRODUCT_CODE,
        SUM(T1.PRICE * T2.SALES_AMOUNT) AS SALES
FROM PRODUCT AS T1 JOIN OFFLINE_SALE AS T2 ON T1.PRODUCT_ID = T2.PRODUCT_ID 
WHERE T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY T1.PRODUCT_CODE
ORDER BY SALES DESC, T1.PRODUCT_CODE ASC;

