SELECT
        T1.ID,
        T3.FISH_NAME,
        T1.LENGTH
FROM FISH_INFO AS T1 
JOIN 
    (
    SELECT 
            FISH_TYPE,
            MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) AS T2 
    ON T1.FISH_TYPE = T2.FISH_TYPE AND T1.LENGTH = T2.MAX_LENGTH 
JOIN
    FISH_NAME_INFO AS T3 ON T1.FISH_TYPE = T3.FISH_TYPE
ORDER BY T1.ID ASC;